rocketmq: 
  config: 
    namesrvAddr: localhost:9876
eureka: 
    instance: 
        leaseRenewalIntervalInSeconds: 2
        leaseExpirationDurationInSeconds: 3
        prefer-ip-address: true
    client:
        registerWithEureka: true
        serviceUrl: 
            defaultZone:  http://eureka-server:8761/eureka/