rocketmq: 
  config: 
    namesrvAddr: rmqserver:9876
eureka: 
    instance: 
        leaseRenewalIntervalInSeconds: 2
        leaseExpirationDurationInSeconds: 3
        prefer-ip-address: true
    client:
        registerWithEureka: true
        serviceUrl: 
            defaultZone:  http://eureka1:8761/eureka/